services:
  - name: django-app
    type: web
    runtime: python3.9
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn image_processor.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: image_processor.onrender.com

  - name: django-worker
    type: worker
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py qcluster
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: image_processor.onrender.com
